# Generated by Django 4.1.3 on 2025-03-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_trainer_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user_id',
        ),
    ]
