# Generated by Django 4.1.3 on 2025-03-16 12:07

import CalorieCounter.fitness.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_trainer_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_in_minutes', models.IntegerField(error_messages={'min_value': 'Duration must be at least 10 seconds.'}, validators=[django.core.validators.MinValueValidator(10)])),
                ('time', models.TimeField()),
                ('date', models.DateField(validators=[CalorieCounter.fitness.validators.validate_date])),
                ('description', models.TextField(max_length=250)),
                ('max_user_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('image_url', models.URLField(error_messages={'url': 'Invalid URL!'}, validators=[django.core.validators.URLValidator()])),
                ('trainer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.trainer')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
