# Generated by Django 4.1.3 on 2025-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_class'),
        ('accounts', '0002_customuser_trainer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_id',
            field=models.ManyToManyField(blank=True, null=True, to='fitness.class'),
        ),
    ]
